### PR TITLE
add increaseSpecificity sheet option

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by iamstarkov** [comment]
Why?

**Comment by kof** [comment]
To be able to disable increased specificity for some local style sheet. Some things don't need it. For e.g. [reset-jss](https://github.com/cssinjs/reset-jss) and [normalize-jss](https://github.com/cssinjs/normalize-jss).

**Comment by kof** [comment]
I think actually plugins should be disablable on a sheet level in general, maybe this is something we need to consider in the jss core.

**Comment by kof** [comment]
I found only a few cases so far where plugin needs to be disabled per sheet, which is jss-isolate. I guess it is rarely the case, so it might be ok if plugin itself implements this option handling as I did in this pr.

**Comment by iamstarkov** [comment]
`+ jss-increase-specificity@0.3.0`

**Pull request merged**
